# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_pessoa_encoding_distance_to_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='faixa_altura',
            field=models.CharField(blank=True, choices=[('anao', 'Anão'), ('ate_160', 'Até 1,60 m'), ('de_160_ate_170', 'De 1,60 até 1,70 m'), ('de_170_ate_180', 'De 1,70 até 1,80 m'), ('acima_de_180', 'Acima de 1,80 m')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='idade_aparente',
            field=models.CharField(blank=True, choices=[('ate_18_anos', 'Até 18 anos'), ('de_19_ate_30_anos', 'De 19 até 30 anos'), ('de_31_ate_45_anos', 'De 31 até 45 anos'), ('de_46_ate_65_anos', 'De 46 até 65 anos'), ('acima_de_65_anos', 'Acima de 65 anos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cor_cabelos',
            field=models.CharField(blank=True, choices=[('aco', 'Aço'), ('branco', 'Branco'), ('castanho_claro', 'Castanho Claro'), ('castanho_escuro', 'Castanho Escuro'), ('com_mexas_ou_faixas', 'Com Mexas ou Faixas'), ('louro', 'Louro'), ('preto', 'Preto'), ('ruivo', 'Ruivo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cor_olhos',
            field=models.CharField(blank=True, choices=[('azuis', 'Azuis'), ('castanhos_claros', 'Castanhos Claros'), ('castanhos_escuros', 'Castanhos Escuros'), ('cinzentos', 'Cinzentos'), ('castanhos', 'Castanhos'), ('desiguais_na_cor', 'Desiguais na Cor'), ('pretos', 'Pretos'), ('verdes', 'Verdes'), ('violetas', 'Violetas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cor_pele',
            field=models.CharField(blank=True, choices=[('albino', 'Albino'), ('amarela', 'Amarela'), ('branca', 'Branca'), ('negra', 'Negra'), ('parda', 'Parda'), ('vermelha', 'Vermelha')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=100, null=True),
        ),
    ]
