# Generated by Django 2.2 on 2019-04-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0013_pessoa_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='ativo',
            new_name='is_active',
        ),
    ]
