# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0004_auto_20170721_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_fisico',
            field=models.CharField(blank=True, choices=[('aco', 'Aço'), ('branco', 'Branco'), ('castanho_claro', 'Castanho Claro'), ('castanho_escuro', 'Castanho Escuro'), ('com_mexas_ou_faixas', 'Com Mexas ou Faixas'), ('louro', 'Louro'), ('preto', 'Preto'), ('ruivo', 'Ruivo')], max_length=254, null=True),
        ),
    ]
