# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0005_auto_20170721_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='esta_desaparecido',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='possui_cicatriz',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='possui_deficiencia',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='possui_tatuagem',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sofreu_amputacao',
            field=models.NullBooleanField(),
        ),
    ]
