# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0007_auto_20170721_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_fisico',
            field=models.CharField(blank=True, choices=[('magro', 'Magro'), ('normal', 'Normal'), ('gordo', 'Gordo'), ('forte', 'Forte')], max_length=254, null=True),
        ),
    ]
