"""
Django settings for desaparecidos_rj_web project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'desaparecidos_rj_web/static'),
)

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sk=#9f^9%hy_8-2*z591y*c2i#!ieq8!yk$r6bw3otqs9y7)$%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.1.4", "127.0.0.1", "desaparecidos.herokuapp.com", "desaparecidos-rj-web1.herokuapp.com"]

CORS_ORIGIN_ALLOW_ALL = True
# Application definition
INSTALLED_APPS = [
    'webserver.apps.WebserverConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'desaparecidos_rj_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'desaparecidos_rj_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#DATABASES = {
#    'default': dj_database_url.config(default='postgres://jlhdzikewiovee:03fd466c7d024db8268d86cb1320896a1d56336ae9cdb99ed197344854f95bee@ec2-54-83-29-34.compute-1.amazonaws.com:5432/d98sa37euvn8lt')
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'desaparecidos_rj.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = "/webserver/login/"


# Log dedfinitions

LOG_LEVEL = "DEBUG" if DEBUG else "INFO"
LOG_FILES_DIR = ""  # By default, the current directory.
EVENTS_LOG_FILE_NAME = "desaparecidos-rj.log"
REQUESTS_LOG_FILE_NAME = "req-desaparecidos-rj.log"


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '[%(asctime)s] [%(name)s] [%(funcName)s] [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            #'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
            #'style': '{',
        },
        'file': {
            'format': '[%(asctime)s] [%(name)s] [%(funcName)s] [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            #'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
            #'style': '{',
        },
    },
    #'filters': {
    #    'require_debug_false': {
    #        '()': 'django.utils.log.RequireDebugFalse'
    #    }
    #},
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
        'file': {
            'level': LOG_LEVEL,
            'class': "logging.FileHandler",
            'formatter': 'file',
            'filename': LOG_FILES_DIR + EVENTS_LOG_FILE_NAME,
        },
    },
    'loggers': {
        #'apps.WebserverConfig': {
        #    'handlers': ["file"],
        #    'level': LOG_LEVEL,
        #    'propagate': True,
        #},
        '': {
            'level': 'DEBUG',
            'handlers': ['console', 'file']
        }
    },
}
